packages:
  - "apps"
  - "apps/*"
  - "packages"
  - "packages/*"
  - "examples"
  - "examples/*"
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1112.0'
