import { ContentBlockSchema } from "../page-document/v1/index.js"

export const validBlockFixtures = [
  ContentBlockSchema.parse({
    id: "paragraph-intro",
    type: "paragraph",
    text: "Portable structured content.",
    extensions: { "geo.example/emphasis": "lead" },
  }),
  ContentBlockSchema.parse({ id: "heading-contract", type: "heading", level: 2, text: "Contract" }),
  ContentBlockSchema.parse({
    id: "image-map",
    type: "image",
    src: "/media/map.webp",
    alt: "A map generated by Geo Foundry",
    width: 1200,
    height: 800,
  }),
  ContentBlockSchema.parse({
    id: "quote-portable",
    type: "quote",
    text: "Content should outlive its renderer.",
    attribution: "Geo Foundry",
  }),
  ContentBlockSchema.parse({
    id: "list-benefits",
    type: "list",
    style: "unordered",
    items: ["Strict contracts", "Portable rendering"],
  }),
  ContentBlockSchema.parse({
    id: "table-support",
    type: "table",
    columns: ["Page", "Supported"],
    rows: [["Article", "Yes"]],
    caption: "P0 page support",
  }),
  ContentBlockSchema.parse({
    id: "faq-schema",
    type: "faq",
    items: [{ question: "Is the schema strict?", answer: "Yes, undeclared fields fail." }],
  }),
  ContentBlockSchema.parse({
    id: "callout-portable",
    type: "callout",
    tone: "info",
    title: "Portable",
    text: "The contract has no renderer dependency.",
  }),
  ContentBlockSchema.parse({
    id: "code-parse",
    type: "code",
    language: "typescript",
    code: "PageDocumentSchema.parse(input)",
  }),
  ContentBlockSchema.parse({
    id: "video-overview",
    type: "video",
    src: "https://media.site-a.test/overview.mp4",
    title: "Geo Foundry overview",
    poster: "/media/overview.webp",
  }),
  ContentBlockSchema.parse({
    id: "embed-map",
    type: "embed",
    provider: "maps",
    url: "https://maps.site-a.test/embed/guide",
    title: "Guide map",
  }),
  ContentBlockSchema.parse({
    id: "references-sources",
    type: "references",
    items: [{ citationId: "citation-prd", label: "Product requirements" }],
  }),
] as const

export const invalidBlockFixtures = {
  paragraph: [
    { type: "paragraph", text: "" },
    { type: "paragraph", text: "Text", html: "<p>Text</p>" },
  ],
  heading: [
    { type: "heading", level: 1, text: "Top level" },
    { type: "heading", level: 2, text: "" },
  ],
  image: [
    { type: "image", src: "/media/map.webp", alt: "" },
    { type: "image", alt: "Missing source" },
  ],
  quote: [
    { type: "quote", text: "" },
    { type: "quote", text: "Quote", citeUrl: "ftp://site-a.test/source" },
  ],
  list: [
    { type: "list", style: "unordered", items: [] },
    { type: "list", style: "bullets", items: ["Item"] },
  ],
  table: [
    { type: "table", columns: [], rows: [["Value"]] },
    { type: "table", columns: ["Column"], rows: [] },
  ],
  faq: [
    { type: "faq", items: [] },
    { type: "faq", items: [{ question: "Question", answer: "" }] },
  ],
  callout: [
    { type: "callout", tone: "neutral", text: "Message" },
    { type: "callout", tone: "info", text: "" },
  ],
  code: [
    { type: "code", language: "typescript", code: "" },
    { type: "code", language: "", code: "const value = 1" },
  ],
  video: [
    { type: "video", src: "ftp://site-a.test/video", title: "Video" },
    { type: "video", src: "/media/video.mp4", title: "" },
  ],
  embed: [
    { type: "embed", provider: "maps", url: "ftp://site-a.test/map", title: "Map" },
    { type: "embed", provider: "", url: "https://site-a.test/map", title: "Map" },
  ],
  references: [
    { type: "references", items: [] },
    { type: "references", items: [{ citationId: "INVALID ID", label: "Source" }] },
  ],
} as const
