import { describe, expect, it } from "vitest"

import {
  compileArticle,
  compileListingPage,
  compileNotFoundPage,
  compileRedirectPage,
  compileSite,
  type CompileRequest,
} from "../src/index.js"

const site = {
  canonicalDomain: "site-a.test",
  locale: "en-US",
  name: "Site A",
  seoDefaults: { description: "Site A default description.", title: "Site A" },
  siteId: "site-a",
  timezone: "UTC",
}

const edition = {
  assessmentInputHash: "a".repeat(64),
  assessmentState: "passed",
  body: [
    { blockType: "heading", level: "2", text: "Deterministic release gates" },
    { blockType: "paragraph", text: "Every edition passes three gates before it ships." },
    { blockType: "image", mediaId: "media-map", alt: "A map generated by Geo Foundry" },
  ],
  categories: ["guides"],
  citations: [
    { id: "citation-prd", title: "Product requirements", url: "https://site-a.test/sources/prd" },
  ],
  contentId: 12,
  editionId: 101,
  modifiedAt: "2026-08-17T11:00:00Z",
  publishedAt: "2026-08-17T10:00:00Z",
  secondaryTopics: ["gates"],
  siteId: "site-a",
  status: "approved",
  summary: "How deterministic gates protect releases.",
  tags: ["contracts"],
  title: "Deterministic release gates",
  urlPathname: "/guides/release-gates",
  urlStatus: "active",
}

const media = [
  {
    alt: "A map generated by Geo Foundry",
    height: 800,
    id: "media-map",
    path: "/media/map.webp",
    width: 1200,
  },
]

const request = (): CompileRequest => ({
  clock: { now: "2026-08-19T00:00:00Z" },
  compilerVersion: "geo-compiler-1",
  editions: [{ ...edition, media }],
  listings: {
    articles: { pathname: "/articles", pageSize: 20 },
    categories: [{ id: "cat-guides", pathname: "/guides", slug: "guides", title: "Guides" }],
    tags: [
      { id: "tag-contracts", pathname: "/tags/contracts", slug: "contracts", title: "Contracts" },
    ],
  },
  notFound: { pathname: "/not-found" },
  redirects: [
    { fromPathname: "/old-guides", targetUrl: "https://site-a.test/guides/release-gates" },
  ],
  site,
})

describe("compileSite golden output", () => {
  it("produces one deterministic document per page type, sorted by pathname", async () => {
    const output = await compileSite(request())
    const documents = output.documents.map((document) => document.pathname)
    expect(documents).toEqual([
      "/articles",
      "/guides",
      "/guides/release-gates",
      "/not-found",
      "/old-guides",
      "/tags/contracts",
    ])
    const article = output.documents.find(
      (document) => document.pathname === "/guides/release-gates",
    )
    expect(article?.pageType).toBe("article")
    const parsed = JSON.parse(article?.canonical ?? "{}")
    expect(parsed.pageType).toBe("article")
    expect(parsed.route.canonicalUrl).toBe("https://site-a.test/guides/release-gates")
    expect(parsed.metadata.publishedAt).toBe("2026-08-17T10:00:00Z")
    expect(parsed.body).toHaveLength(3)
    expect(parsed.body[2]).toMatchObject({ src: "/media/map.webp", type: "image" })
    expect(parsed.citations).toHaveLength(1)
    const listing = output.documents.find((document) => document.pathname === "/articles")
    const listingParsed = JSON.parse(listing?.canonical ?? "{}")
    expect(listingParsed.pageType).toBe("article-list")
    expect(listingParsed.items).toHaveLength(1)
    expect(listingParsed.pagination).toEqual({
      page: 1,
      pageSize: 20,
      totalItems: 1,
      totalPages: 1,
    })
    const category = JSON.parse(
      output.documents.find((document) => document.pathname === "/guides")?.canonical ?? "{}",
    )
    expect(category.pageType).toBe("category")
    const tag = JSON.parse(
      output.documents.find((document) => document.pathname === "/tags/contracts")?.canonical ??
        "{}",
    )
    expect(tag.pageType).toBe("tag")
    const redirect = JSON.parse(
      output.documents.find((document) => document.pathname === "/old-guides")?.canonical ?? "{}",
    )
    expect(redirect.pageType).toBe("redirect")
    expect(redirect.redirect).toEqual({
      statusCode: 301,
      targetUrl: "https://site-a.test/guides/release-gates",
    })
    expect(redirect.seo.robots.index).toBe(false)
    const notFound = JSON.parse(
      output.documents.find((document) => document.pathname === "/not-found")?.canonical ?? "{}",
    )
    expect(notFound.pageType).toBe("not-found")
    expect(notFound.seo.robots.index).toBe(false)
    expect(output.compilerVersion).toBe("geo-compiler-1")
  })
})

describe("single-page compilers", () => {
  it("compiles an article page that validates against the v1 schema", async () => {
    const page = await compileArticle({
      clock: { now: "2026-08-19T00:00:00Z" },
      edition: { ...edition, media },
      site,
    })
    expect(page.pageType).toBe("article")
    expect(page.route.pathname).toBe("/guides/release-gates")
  })

  it("compiles listing, redirect, and not-found pages", async () => {
    const list = await compileListingPage({
      clock: { now: "2026-08-19T00:00:00Z" },
      kind: "category",
      pathname: "/guides",
      items: [
        {
          description: edition.summary,
          pageId: "page-101",
          pathname: edition.urlPathname,
          title: edition.title,
        },
      ],
      pagination: { page: 1, pageSize: 20, totalItems: 1, totalPages: 1 },
      site,
      title: "Guides",
    })
    expect(list.pageType).toBe("category")
    const redirect = await compileRedirectPage({
      clock: { now: "2026-08-19T00:00:00Z" },
      fromPathname: "/old-guides",
      site,
      targetUrl: "https://site-a.test/guides/release-gates",
    })
    expect(redirect.pageType).toBe("redirect")
    const notFound = await compileNotFoundPage({
      clock: { now: "2026-08-19T00:00:00Z" },
      pathname: "/not-found",
      site,
    })
    expect(notFound.pageType).toBe("not-found")
  })
})
