import { readdir, readFile } from "node:fs/promises"
import { describe, expect, it } from "vitest"

import { canonicalJson, compileSite, type CompileRequest } from "../src/index.js"

const request = (): CompileRequest => ({
  clock: { now: "2026-08-19T00:00:00Z" },
  compilerVersion: "geo-compiler-1",
  editions: [
    {
      assessmentInputHash: "a".repeat(64),
      assessmentState: "passed",
      body: [
        { blockType: "heading", level: "2", text: "Deterministic release gates" },
        { blockType: "paragraph", text: "Every edition passes three gates before it ships." },
        { blockType: "image", mediaId: "media-map", alt: "A map generated by Geo Foundry" },
      ],
      categories: ["guides"],
      citations: [
        {
          id: "citation-prd",
          title: "Product requirements",
          url: "https://site-a.test/sources/prd",
        },
      ],
      contentId: 12,
      editionId: 101,
      media: [
        {
          alt: "A map generated by Geo Foundry",
          height: 800,
          id: "media-map",
          path: "/media/map.webp",
          width: 1200,
        },
      ],
      modifiedAt: "2026-08-17T11:00:00Z",
      publishedAt: "2026-08-17T10:00:00Z",
      secondaryTopics: ["gates"],
      siteId: "site-a",
      status: "approved",
      summary: "How deterministic gates protect releases.",
      tags: ["contracts"],
      title: "Deterministic release gates",
      urlPathname: "/guides/release-gates",
      urlStatus: "active",
    },
  ],
  listings: {
    articles: { pathname: "/articles", pageSize: 20 },
    categories: [{ id: "cat-guides", pathname: "/guides", slug: "guides", title: "Guides" }],
    tags: [
      { id: "tag-contracts", pathname: "/tags/contracts", slug: "contracts", title: "Contracts" },
    ],
  },
  notFound: { pathname: "/not-found" },
  redirects: [
    { fromPathname: "/old-guides", targetUrl: "https://site-a.test/guides/release-gates" },
  ],
  site: {
    canonicalDomain: "site-a.test",
    locale: "en-US",
    name: "Site A",
    seoDefaults: { description: "Site A default description.", title: "Site A" },
    siteId: "site-a",
    timezone: "UTC",
  },
})

describe("golden fixtures per page type", () => {
  it("matches every committed golden file byte-for-byte in canonical form", async () => {
    const output = await compileSite(request())
    const goldenDirectory = new URL("./golden/", import.meta.url)
    const files = (await readdir(goldenDirectory)).filter((name) => name.endsWith(".json"))
    expect(files).toHaveLength(6)
    for (const name of files) {
      const golden = JSON.parse(await readFile(new URL(name, goldenDirectory), "utf8"))
      const expectedCanonical = canonicalJson(golden)
      const document = output.documents.find((entry) => entry.pathname === golden.route?.pathname)
      expect(document, `compiled counterpart of ${name}`).toBeDefined()
      expect(document?.canonical).toBe(expectedCanonical)
    }
  })
})
