import { describe, expect, it } from "vitest"

import {
  COMPILER_ERROR,
  compileArticle,
  geoMediaSrcOf,
  type CompileSite,
} from "../src/index.js"

const site: CompileSite = {
  canonicalDomain: "site-a.test",
  locale: "en-US",
  name: "Site A",
  seoDefaults: { description: "Site A default description.", title: "Site A" },
  organization: { logoUrl: "/media/logo.svg", name: "Site A Media" },
  siteId: "site-a",
  timezone: "UTC",
}

const baseEdition = {
  assessmentInputHash: "a".repeat(64),
  assessmentState: "passed",
  author: { id: "author-ada", name: "Ada Chen", url: "https://site-a.test/authors/ada-chen" },
  categories: ["guides"],
  contentId: 12,
  editionId: 101,
  modifiedAt: "2026-08-17T11:00:00Z",
  publishedAt: "2026-08-17T10:00:00Z",
  siteId: "site-a",
  status: "approved",
  summary: "Image src handling",
  tags: ["images"],
  title: "Image src handling",
  urlPathname: "/guides/image-src",
  urlStatus: "active",
}

const media = [
  {
    alt: "A map generated by Geo Foundry",
    height: 800,
    id: "media-11",
    path: "/media/map.webp",
    tenantId: 413,
    width: 1200,
  },
]

const article = async (
  body: readonly unknown[],
  snapshotMedia: readonly unknown[] = media,
) =>
  compileArticle({
    clock: { now: "2026-08-19T00:00:00Z" },
    edition: { ...baseEdition, body, media: snapshotMedia as never },
    site,
  })

const expectCode = async (promise: Promise<unknown>, code: string) =>
  await expect(promise).rejects.toMatchObject({ code })

describe("geo media src normalization", () => {
  it("normalizes editor upload refs and direct media paths to /media/<filename>", () => {
    expect(geoMediaSrcOf("/api/media/file/map.webp")).toBe("/media/map.webp")
    expect(geoMediaSrcOf("/media/map.webp")).toBe("/media/map.webp")
  })

  it("rejects non geo refs and path traversal", () => {
    expect(geoMediaSrcOf("https://cdn.example.com/x.png")).toBeNull()
    expect(geoMediaSrcOf("/uploads/x.png")).toBeNull()
    expect(geoMediaSrcOf("images/x.png")).toBeNull()
    expect(geoMediaSrcOf("/api/media/file/a/b.png")).toBeNull()
    expect(geoMediaSrcOf("/api/media/file/../secret.png")).toBeNull()
    expect(geoMediaSrcOf("/media/")).toBeNull()
  })
})

describe("image block src-only compilation", () => {
  it("rewrites an in-site geo media ref to the artifact media path", async () => {
    const page = await article([{ blockType: "image", src: "/api/media/file/map.webp" }])
    expect(page.body).toHaveLength(1)
    expect(page.body[0]).toMatchObject({ src: "/media/map.webp", type: "image" })
  })

  it("falls back to the media snapshot alt when the block alt is empty", async () => {
    const page = await article([
      { alt: "", blockType: "image", src: "/api/media/file/map.webp" },
    ])
    const block = page.body[0]
    expect(block.type).toBe("image")
    if (block.type !== "image") return
    expect(block.alt).toBe("A map generated by Geo Foundry")
    expect(block.width).toBe(1200)
    expect(block.height).toBe(800)
  })

  it("keeps a direct /media/ src untouched", async () => {
    const page = await article([{ blockType: "image", src: "/media/map.webp", alt: "Direct" }])
    expect(page.body[0]).toMatchObject({ alt: "Direct", src: "/media/map.webp", type: "image" })
  })

  it("keeps an external https image with alt as-is", async () => {
    const page = await article([
      {
        alt: "An external diagram",
        blockType: "image",
        src: "https://cdn.example.com/diagram.png",
      },
    ])
    expect(page.body[0]).toMatchObject({
      alt: "An external diagram",
      src: "https://cdn.example.com/diagram.png",
      type: "image",
    })
  })

  it("rejects an external image without alt text", async () => {
    await expectCode(
      article([{ blockType: "image", src: "https://cdn.example.com/no-alt.png" }]),
      COMPILER_ERROR.MEDIA_ALT_MISSING,
    )
  })

  it("rejects unsupported relative paths with MEDIA_SRC_UNSUPPORTED", async () => {
    await expectCode(
      article([{ blockType: "image", src: "/uploads/local.png", alt: "local" }]),
      COMPILER_ERROR.MEDIA_SRC_UNSUPPORTED,
    )
    await expectCode(
      article([{ blockType: "image", src: "images/local.png", alt: "local" }]),
      COMPILER_ERROR.MEDIA_SRC_UNSUPPORTED,
    )
  })

  it("rejects a geo media ref without a snapshot entry", async () => {
    await expectCode(
      article([{ blockType: "image", src: "/api/media/file/missing.webp" }], []),
      COMPILER_ERROR.MEDIA_MISSING,
    )
  })

  it("rejects an image block with neither mediaId nor src", async () => {
    await expectCode(article([{ blockType: "image" }]), COMPILER_ERROR.MEDIA_MISSING)
  })

  it("keeps the mediaId path working against the snapshot", async () => {
    const page = await article([
      { blockType: "image", mediaId: "media-11", alt: "A map generated by Geo Foundry" },
    ])
    expect(page.body[0]).toMatchObject({ src: "/media/map.webp", type: "image" })
  })
})
