import { describe, expect, it } from "vitest"

import {
  COMPILER_ERROR,
  type CompileRequest,
  CompilerError,
  compileArticle,
  compileListingPage,
  compileSite,
} from "../src/index.js"

const site = {
  canonicalDomain: "site-a.test",
  locale: "en-US",
  name: "Site A",
  seoDefaults: { description: "Site A default description.", title: "Site A" },
  organization: { logoUrl: "/media/logo.svg", name: "Site A Media" },
  siteId: "site-a",
  timezone: "UTC",
}

const edition = {
  assessmentInputHash: "a".repeat(64),
  assessmentState: "passed",
  author: { id: "author-ada", name: "Ada Chen", url: "https://site-a.test/authors/ada-chen" },
  body: [
    { blockType: "heading", level: "2", text: "Deterministic release gates" },
    { blockType: "paragraph", text: "Every edition passes three gates before it ships." },
    { blockType: "image", mediaId: "media-map", alt: "A map generated by Geo Foundry" },
  ],
  categories: ["guides"],
  citations: [
    { id: "citation-prd", title: "Product requirements", url: "https://site-a.test/sources/prd" },
  ],
  contentId: 12,
  editionId: 101,
  media: [
    {
      alt: "A map generated by Geo Foundry",
      height: 800,
      id: "media-map",
      path: "/media/map.webp",
      width: 1200,
    },
  ],
  modifiedAt: "2026-08-17T11:00:00Z",
  publishedAt: "2026-08-17T10:00:00Z",
  secondaryTopics: ["gates"],
  siteId: "site-a",
  status: "approved",
  summary: "How deterministic gates protect releases.",
  tags: ["contracts"],
  title: "Deterministic release gates",
  urlPathname: "/guides/release-gates",
  urlStatus: "active",
}

const request = (): CompileRequest => ({
  clock: { now: "2026-08-19T00:00:00Z" },
  compilerVersion: "geo-compiler-1",
  editions: [edition],
  listings: {
    articles: { pathname: "/articles", pageSize: 20 },
    categories: [{ id: "cat-guides", pathname: "/guides", slug: "guides", title: "Guides" }],
    tags: [
      { id: "tag-contracts", pathname: "/tags/contracts", slug: "contracts", title: "Contracts" },
    ],
  },
  notFound: { pathname: "/not-found" },
  redirects: [
    { fromPathname: "/old-guides", targetUrl: "https://site-a.test/guides/release-gates" },
  ],
  site,
})

describe("typed rejections", () => {
  const expectCode = async (promise: Promise<unknown>, code: string) =>
    await expect(promise).rejects.toMatchObject({ code })

  it("rejects a draft edition", async () => {
    await expectCode(
      compileArticle({
        clock: { now: "2026-08-19T00:00:00Z" },
        edition: { ...edition, media: edition.media, status: "draft" },
        site,
      }),
      COMPILER_ERROR.EDITION_NOT_APPROVED,
    )
  })

  it("rejects a failed assessment", async () => {
    await expectCode(
      compileArticle({
        clock: { now: "2026-08-19T00:00:00Z" },
        edition: { ...edition, media: edition.media, assessmentState: "failed" },
        site,
      }),
      COMPILER_ERROR.ASSESSMENT_NOT_PASSED,
    )
  })

  it("rejects an edition without an active URL", async () => {
    await expectCode(
      compileArticle({
        clock: { now: "2026-08-19T00:00:00Z" },
        edition: { ...edition, media: edition.media, urlStatus: "reserved" },
        site,
      }),
      COMPILER_ERROR.URL_NOT_ACTIVE,
    )
  })

  it("rejects media references without a snapshot entry", async () => {
    await expectCode(
      compileArticle({
        clock: { now: "2026-08-19T00:00:00Z" },
        edition: { ...edition, media: [] },
        site,
      }),
      COMPILER_ERROR.MEDIA_MISSING,
    )
  })

  it("rejects unsupported edition blocks", async () => {
    await expectCode(
      compileArticle({
        clock: { now: "2026-08-19T00:00:00Z" },
        edition: {
          ...edition,
          media: edition.media,
          body: [...edition.body, { blockType: "hologram", text: "unsupported" }],
        },
        site,
      }),
      COMPILER_ERROR.BLOCK_UNSUPPORTED,
    )
  })

  it("rejects timezone-dependent timestamps", async () => {
    await expectCode(
      compileArticle({
        clock: { now: "2026-08-19T00:00:00Z" },
        edition: { ...edition, media: edition.media, publishedAt: "2026-08-17T10:00:00+02:00" },
        site,
      }),
      COMPILER_ERROR.INSTANT_NOT_UTC,
    )
  })

  it("rejects duplicate document pathnames (unstable ordering)", async () => {
    const input = request()
    const first = input.editions[0]
    if (first === undefined) {
      throw new Error("fixture edition missing")
    }
    const clash = { ...first, editionId: 102, contentId: 13 }
    await expectCode(
      compileSite({ ...input, editions: [...input.editions, clash] }),
      COMPILER_ERROR.PATH_DUPLICATE,
    )
  })

  it("rejects duplicate listing item pathnames", async () => {
    await expectCode(
      compileListingPage({
        clock: { now: "2026-08-19T00:00:00Z" },
        kind: "category",
        pathname: "/guides",
        items: [
          { pageId: "a", pathname: "/x", title: "A", description: "d" },
          { pageId: "b", pathname: "/x", title: "B", description: "d" },
        ],
        pagination: { page: 1, pageSize: 20, totalItems: 2, totalPages: 1 },
        site,
        title: "Guides",
      }),
      COMPILER_ERROR.PATH_DUPLICATE,
    )
  })

  it("rejects an edition whose URL lives on another domain (wrong-domain canonical)", async () => {
    await expectCode(
      compileArticle({
        clock: { now: "2026-08-19T00:00:00Z" },
        edition: { ...edition, media: edition.media, urlDomain: "site-b.test" },
        site,
      }),
      COMPILER_ERROR.SEO_CANONICAL_WRONG_DOMAIN,
    )
  })

  it("rejects a malformed canonical domain", async () => {
    await expectCode(
      compileArticle({
        clock: { now: "2026-08-19T00:00:00Z" },
        edition: { ...edition, media: edition.media },
        site: { ...site, canonicalDomain: "https://site-a.test" },
      }),
      COMPILER_ERROR.SEO_CANONICAL_WRONG_DOMAIN,
    )
  })

  it("rejects modifiedAt preceding publishedAt", async () => {
    await expectCode(
      compileArticle({
        clock: { now: "2026-08-19T00:00:00Z" },
        edition: { ...edition, media: edition.media, modifiedAt: "2026-08-17T09:00:00Z" },
        site,
      }),
      COMPILER_ERROR.SEO_DATE_ORDER_INVALID,
    )
  })

  it("rejects an article without an author (required JSON-LD field)", async () => {
    const { author: _author, ...withoutAuthor } = edition
    await expectCode(
      compileArticle({
        clock: { now: "2026-08-19T00:00:00Z" },
        edition: withoutAuthor,
        site,
      }),
      COMPILER_ERROR.SEO_REQUIRED_FIELD_MISSING,
    )
  })

  it("rejects an article when the site has no publisher organization", async () => {
    const { organization: _organization, ...withoutOrg } = site
    await expectCode(
      compileArticle({
        clock: { now: "2026-08-19T00:00:00Z" },
        edition: { ...edition, media: edition.media },
        site: withoutOrg,
      }),
      COMPILER_ERROR.SEO_REQUIRED_FIELD_MISSING,
    )
  })

  it("rejects a news article without a hero image", async () => {
    await expectCode(
      compileArticle({
        clock: { now: "2026-08-19T00:00:00Z" },
        edition: {
          ...edition,
          media: edition.media,
          articleKind: "news",
          body: [
            { blockType: "heading", level: "2", text: "Deterministic release gates" },
            { blockType: "paragraph", text: "Every edition passes three gates before it ships." },
          ],
        },
        site,
      }),
      COMPILER_ERROR.SEO_REQUIRED_FIELD_MISSING,
    )
  })

  it("rejects a redirect that targets its own canonical URL", async () => {
    await expectCode(
      compileSite({
        ...request(),
        redirects: [{ fromPathname: "/old-guides", targetUrl: "/old-guides" }],
      }),
      COMPILER_ERROR.SEO_REDIRECT_CANONICAL_MISMATCH,
    )
  })

  it("exposes a typed error name", () => {
    const error = new CompilerError(COMPILER_ERROR.EDITION_NOT_APPROVED, "edition 1 is draft")
    expect(error.name).toBe("CompilerError")
    expect(error.message).toContain("COMPILER_EDITION_NOT_APPROVED")
  })
})
