import { describe, expect, it } from "vitest"

import {
  buildArticleGraph,
  buildListingGraph,
  buildWebPageGraph,
  COMPILER_ERROR,
  dedupeStructuredData,
  type GraphSite,
} from "../src/index.js"

const site: GraphSite = {
  canonicalDomain: "site-a.test",
  organization: { logoUrl: "/media/logo.svg", name: "Site A Media" },
}

const author = { id: "author-ada", name: "Ada Chen", url: "https://site-a.test/authors/ada-chen" }

const heroImage = {
  caption: "A map generated by Geo Foundry",
  height: 800,
  url: "https://site-a.test/media/map.webp",
  width: 1200,
}

const breadcrumbs = [
  { pathname: "/", title: "Site A" },
  { pathname: "/guides", title: "Guides" },
]

const articleInput = {
  articleKind: "article" as const,
  author,
  breadcrumbs,
  canonicalUrl: "https://site-a.test/guides/release-gates",
  dateModified: "2026-08-17T11:00:00Z",
  datePublished: "2026-08-17T10:00:00Z",
  description: "How deterministic gates protect releases.",
  heroImage,
  site,
  title: "Deterministic release gates",
}

const expectCode = (act: () => unknown, code: string) =>
  expect(act).toThrowError(expect.objectContaining({ code }))

describe("article JSON-LD graph", () => {
  it("links Article, ImageObject, Person, Organization, and BreadcrumbList in a stable order", () => {
    const graph = buildArticleGraph(articleInput)
    expect(graph.map((node) => node.type)).toEqual([
      "Article",
      "ImageObject",
      "Person",
      "Organization",
      "BreadcrumbList",
    ])
    expect(graph[0]).toMatchObject({
      author: { name: "Ada Chen", url: "https://site-a.test/authors/ada-chen" },
      dateModified: "2026-08-17T11:00:00Z",
      datePublished: "2026-08-17T10:00:00Z",
      description: "How deterministic gates protect releases.",
      headline: "Deterministic release gates",
      id: "#article",
      image: "https://site-a.test/media/map.webp",
      url: "https://site-a.test/guides/release-gates",
    })
    expect(graph[1]).toMatchObject({
      caption: "A map generated by Geo Foundry",
      height: 800,
      id: "#primary-image",
      url: "https://site-a.test/media/map.webp",
      width: 1200,
    })
    expect(graph[3]).toMatchObject({
      id: "#organization",
      logo: "https://site-a.test/media/logo.svg",
      name: "Site A Media",
      url: "https://site-a.test/",
    })
  })

  it("emits NewsArticle for the news kind and requires its hero image", () => {
    const graph = buildArticleGraph({ ...articleInput, articleKind: "news" })
    expect(graph[0]?.type).toBe("NewsArticle")
    const { heroImage: _heroImage, ...withoutHero } = articleInput
    expectCode(
      () => buildArticleGraph({ ...withoutHero, articleKind: "news" }),
      COMPILER_ERROR.SEO_REQUIRED_FIELD_MISSING,
    )
  })

  it("omits the image node when no hero exists", () => {
    const { heroImage: _heroImage, ...withoutHero } = articleInput
    const graph = buildArticleGraph(withoutHero)
    expect(graph.map((node) => node.type)).toEqual([
      "Article",
      "Person",
      "Organization",
      "BreadcrumbList",
    ])
    expect("image" in (graph[0] ?? {})).toBe(false)
  })

  it("requires an author and a publisher organization", () => {
    const { author: _author, ...withoutAuthor } = articleInput
    expectCode(() => buildArticleGraph(withoutAuthor), COMPILER_ERROR.SEO_REQUIRED_FIELD_MISSING)
    const { organization: _organization, ...withoutOrg } = site
    expectCode(
      () => buildArticleGraph({ ...articleInput, site: withoutOrg }),
      COMPILER_ERROR.SEO_REQUIRED_FIELD_MISSING,
    )
  })
})

describe("structured data deduplication", () => {
  const webpage = {
    id: "#webpage",
    name: "Page not found",
    type: "WebPage" as const,
    url: "https://site-a.test/not-found",
  }

  it("collapses byte-identical nodes", () => {
    expect(dedupeStructuredData([webpage, { ...webpage }])).toHaveLength(1)
  })

  it("fails when distinct nodes claim the same JSON-LD id", () => {
    expectCode(
      () =>
        dedupeStructuredData([
          webpage,
          {
            id: "#webpage",
            name: "A different page",
            type: "WebPage",
            url: "https://site-a.test/x",
          },
        ]),
      COMPILER_ERROR.SEO_STRUCTURED_DATA_ID_DUPLICATE,
    )
  })

  it("keeps distinct ids on the same node type", () => {
    expect(
      dedupeStructuredData([
        webpage,
        { id: "#other", name: "Other", type: "WebPage", url: "https://site-a.test/y" },
      ]),
    ).toHaveLength(2)
  })
})

describe("listing and utility graphs", () => {
  it("describes collections and mirrors the breadcrumb trail", () => {
    const graph = buildListingGraph({
      breadcrumbs,
      canonicalUrl: "https://site-a.test/guides",
      description: "Site A default description.",
      title: "Guides",
    })
    expect(graph.map((node) => node.type)).toEqual(["CollectionPage", "BreadcrumbList"])
    expect(graph[1]).toMatchObject({ id: "#breadcrumbs", items: breadcrumbs })
  })

  it("mirrors the visible heading of utility pages", () => {
    const graph = buildWebPageGraph({
      breadcrumbs,
      canonicalUrl: "https://site-a.test/not-found",
      name: "Page not found",
    })
    expect(graph.map((node) => node.type)).toEqual(["WebPage", "BreadcrumbList"])
  })
})
